default: clean final

final:
	g++ -o final  final.cpp  glslprogram.cpp -lm -framework OpenGL -framework GLUT  -Wno-deprecated-declarations -Wno-c++11-compat-deprecated-writable-strings
clean:
	rm final
